AllCops:
  Exclude:
    - db/**/**
    - bin/**
    - config/**/**
    - test/**/**
Metrics/LineLength:
  Max: 160
Metrics/MethodLength:
  Max: 40
Metrics/AbcSize:
  Max: 40
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
