# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ed7f35da6d73ebaf6c87544741f4da44b90dac9c67cf89c6533ca60b0617b2fa2179e1fab5820da2b829ecd7cfffd9de2b7c09b2d1b79c8190df6ff5331fbef8

test:
  secret_key_base: c47bee3d465040f9c1491aad6c4f7d3c2b35aed6679fb390610953f2e12a290d1b5dae05d13d3fc5cf3eaff19073c02126f60222ab53f425346b0061dbdc7100

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
